pipeline {
    agent none

    stages {

        stage('Back-end') {
            agent {
                docker {
                    image 'maven:3.8.1-adoptopenjdk-11'
                }
            }

            steps {

                sh 'mvn --version'

                sh '''
cat > HelloWorld.java <<EOF
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello World from Java Backend!");
    }
}
EOF
'''

                sh 'javac HelloWorld.java'

                sh 'java HelloWorld'
            }
        }

        stage('Front-end') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }

            steps {

                sh 'node --version'

                sh '''
cat > app.js <<EOF
console.log("Hello World from Node Frontend!");
EOF
'''

                sh 'node app.js'
            }
        }
    }
}
